import { Inter } from "next/font/google";
import "./globals.css";
import MainHome from "@/components/main";
import Footer from "@/components/footer";
import Navbar from "@/components/header";

export const __isClient = true;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      <MainHome/>
      <Footer/>
      {children}
      </body>
    </html>
  );
}
